[project]
name = "CAVA"
dynamic = ["version"]
authors = [
    {name="Steven-N-Hart",email="hart.steven@mayo.edu"},
    {name="Hugues-Sicotte", email="hugues.sicotte@gmail.com"}
]
description = "CAVA: Clinical Annotation of Variants"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Bio-Informatics"
]
dependencies = [
    "pybedtools",
    "pysam",
    "crossmap",
    "wget",
    "requests",
    "bx-python",
    "numpy<2"
]

[project.optional-dependencies]
tests = ["pytest"]
release = ["build", "twine"]

[project.scripts]
cava = "cava.CAVA:main"

[project.urls]
"Homepage" = "https://github.com/sicotteh/CAVA"
"Previous" = "https://github.com/Steven-N-Hart/CAVA"

[build-system]
requires = ["setuptools>=61.0", "wheel", "Cython>=3"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
version = {file = "cava/VERSION"}

[tool.setuptools.package-data]
cava = ["*.txt", "*.config", "*.bed", "*.bgz", "*.csv", "*.tbi", "*.fa", "*.idx", "*.tab", "*.tsv", "*.gz", "*.fai", "VERSION", "CHANGELOG"]
"cava.ensembldb" = ["*.txt", "*.gtf.gz", "*.md"]
"cava.ensembldb.data" = ["*.gtf.gz"]
"cava.ensembldb.old" = ["*.txt"]
"cava.data" = ["*.txt", "*.gz", "*.tbi", "*.fa", "*.fai"]
"cava.test" = ["*.txt", "*.vcf", "*.sh", "*.config*", "*.csv"]
defaultdb = ["*.tbi"]
data = ["*.txt", "*.tbi"]
ensembldb = ["*.py"]

[tool.setuptools.packages.find]
where = ["."]
include = ["cava*", "defaultdb", "ensembldb", "data"]
