[tox]
envlist = py39

[testenv]
deps =
    -e.[tests]

commands =
    # NOTE: you can run any command line tool here - not just tests
    python -m unittest cava.test.test_end2end
    python -m unittest cava.test.test_csn
