#!/usr/bin/env python3
"""Filter a GTF to accepted transcripts and normalize contigs to FASTA records.

Assembly-report aliases generated by prepare_reference_fastas.py allow names
such as RefSeq accessions, sequence names, Ensembl names and UCSC-style alt
contig names to resolve to the same underlying FASTA record. This is important
for GSTT1 and other transcripts on GRCh38 alternate/patch sequences.
"""
from __future__ import annotations

import argparse
import csv
import gzip
from pathlib import Path

from validate_gtf_sequences import FastaIndex, open_text, parse_attributes


def open_output(path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.suffix == ".gz":
        return gzip.open(path, "wt", encoding="utf-8", newline="")
    return path.open("w", encoding="utf-8", newline="")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--gtf", type=Path, required=True)
    parser.add_argument("--genome-fasta", type=Path, required=True)
    parser.add_argument("--transcripts", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--mapping-report", type=Path, required=True)
    args = parser.parse_args()

    selected = {
        line.strip()
        for line in args.transcripts.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    }
    if not selected:
        raise SystemExit("Accepted transcript list is empty: {}".format(args.transcripts))

    selected_genes = set()
    with open_text(args.gtf) as handle:
        for line in handle:
            if not line or line.startswith("#"):
                continue
            fields = line.rstrip("\n").split("\t")
            if len(fields) != 9:
                continue
            attrs = parse_attributes(fields[8])
            if attrs.get("transcript_id") in selected and attrs.get("gene_id"):
                selected_genes.add(attrs["gene_id"])

    fasta = FastaIndex(args.genome_fasta)
    mappings = {}
    written_transcripts = set()
    unresolved = []
    try:
        with open_text(args.gtf) as source, open_output(args.output) as output:
            for number, line in enumerate(source, 1):
                if line.startswith("#"):
                    output.write(line)
                    continue
                fields = line.rstrip("\n").split("\t")
                if len(fields) != 9:
                    continue
                attrs = parse_attributes(fields[8])
                transcript_id = attrs.get("transcript_id", "")
                gene_id = attrs.get("gene_id", "")
                keep = transcript_id in selected or (not transcript_id and gene_id in selected_genes)
                if not keep:
                    continue
                original = fields[0]
                try:
                    canonical = fasta.resolve(original)
                except KeyError:
                    unresolved.append((number, original, transcript_id, gene_id))
                    continue
                mappings[original] = canonical
                fields[0] = canonical
                output.write("\t".join(fields) + "\n")
                if transcript_id:
                    written_transcripts.add(transcript_id)
    finally:
        fasta.close()

    missing = sorted(selected - written_transcripts)
    args.mapping_report.parent.mkdir(parents=True, exist_ok=True)
    with args.mapping_report.open("w", encoding="utf-8", newline="") as report:
        writer = csv.writer(report, delimiter="\t", lineterminator="\n")
        writer.writerow(["original_contig", "fasta_record"])
        for original in sorted(mappings):
            writer.writerow([original, mappings[original]])

    if unresolved or missing:
        for number, contig, transcript_id, gene_id in unresolved[:20]:
            print(
                "Unresolved GTF contig at line {}: contig={} transcript={} gene={}".format(
                    number, contig, transcript_id, gene_id
                )
            )
        if len(unresolved) > 20:
            print("... {} additional unresolved rows".format(len(unresolved) - 20))
        if missing:
            print("Accepted transcripts absent after normalization: " + ",".join(missing[:20]))
        if args.output.exists():
            args.output.unlink()
        return 1

    print("{}: {} accepted transcripts; {} contig aliases".format(
        args.output, len(written_transcripts), len(mappings)
    ))
    print(args.mapping_report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
